### ISSUE TITLE
Feature request: do not run filters until email finished being received?

### ISSUE THREAD

**Issue by molitar** [RealRaven2000/quickFilters#255] opened 2024-08-02 08:09 UTC
I have 5 email accounts and a lot of filters and while emails are downloading I am spammed by warning that filter can not be applied.

Error:
The messages could not be filtered to folder 'Informational  on @gmail.com' because adding a message to it failed. Verify that the folder is displaying properly or try to repair it from the folder properties.

If it would wait to emails is finished downloading than run it should fix that problem.

**Comment by RealRaven2000** [comment] 2024-08-02 11:57
Did you try to follow the advice of repairing the folder? You can do this via thr right-click menu on folder tree, then select Properties >> repair folder 

![image](https://github.com/user-attachments/assets/6f0b09dc-d401-4353-b627-997932db7610)

![image](https://github.com/user-attachments/assets/83c8709a-4198-4367-8b2d-9c58252858f8)

I think these are caused by Thunderbird itself, possibly in conjunction with an AntiVirus software interfering - see:

https://support.mozilla.org/en-US/questions/1161295

**Comment by molitar** [comment] 2024-08-04 21:15
OK I will try the repair folder option did not even know it existed.

**Comment by RealRaven2000** [comment] 2024-08-09 16:26
> OK I will try the repair folder option did not even know it existed.

did you manage to fix the underlying issue?

**Comment by molitar** [comment] 2024-08-11 21:17
Hello sorry it took a while to respond I was away from PC for a few days so I had a huge amount of emails.  That seems to have resolved the issue as I had about 70 emails today. So I think that resolved the issue.

**Comment by RealRaven2000** [comment] 2024-08-12 14:57
> Hello sorry it took a while to respond I was away from PC for a few days so I had a huge amount of emails. That seems to have resolved the issue as I had about 70 emails today. So I think that resolved the issue.

nice one, thanks for getting back! I will close this one.

**Closed as completed by RealRaven2000** 2024-08-12 14:57 UTC
