### ISSUE TITLE
problem with filtering on subject

### ISSUE THREAD

**Issue by sandwitch** [RealRaven2000/quickFilters#81] opened 2021-11-28 14:55 UTC
Hi,
I have a problem with filtering on subject, nothing happens at all :)
I have the pro version, some times it complains on my license and after a validate it is okay again, however filtering on subject remains faulty. I must admit I use exquilla for my professional exchange account.
What info do you need to assist me?

regards Mark

**Comment by RealRaven2000** [comment] 2021-11-28 17:56
Can you run just one the filter manually?
Can you export or screenshot it?

**Comment by sandwitch** [comment] 2021-11-28 22:03
Hi thanks for the quickresponse,

If I create a subject filter on my personal gmail account this works, that is why I thought it was exquilla related.
If I run the one filter manually nothing happens, also no output in the filter log. If I try to run a backup of the filters there is no screen to select the output file. On my work computer this screen exists. I'm using my license on two laptops, thought that was permitted. Attached are the screenshots.The email account m.r.lamers@umcutrecht.nl i the exquilla (exchange) work account. 
![Screenshot from 2021-11-28 22-50-28](https://user-images.githubusercontent.com/6674691/143787726-4413c6ba-5433-40ef-92c3-df4b31c0737c.png)
![Screenshot from 2021-11-28 22-49-47](https://user-images.githubusercontent.com/6674691/143787728-de480cd8-5fea-4f95-bf2a-549841f3feab.png)

Thanks for your assistance
Mark

**Comment by sandwitch** [comment] 2021-11-28 22:22
Well now I could create a json file:

{
  "accountName": "exquilla://replaced",
  "rootFolderURL": "ews-mailbox:///home/replaced",
  "date": "2021-11-28T22:12:56.299Z",
  "filters": [
    {
      "filterName": "RedHat » Bug Fix - errata@redhat.com",
      "filterDesc": "",
      "filterType": 273,
      "temporary": false,
      "actionCount": 1,
      "enabled": true,
      "actionList": [
        {
          "type": 1,
          "targetFolderUri": "exquilla://replaced"
        }
      ],
      "searchTerms": [
        {
          "attrib": 1,
          "value": {
            "attrib": 1,
            "str": "errata@redhat.com"
          },
          "booleanAnd": true,
          "beginsGrouping": false,
          "endsGrouping": false
        },
        {
          "attrib": 0,
          "value": {
            "attrib": 0,
            "str": "\"[Bug Fix Advisory]\""
          },
          "booleanAnd": true,
          "beginsGrouping": false,
          "endsGrouping": false
        },
        {
          "attrib": 5,
          "op": 2,
          "value": {
            "attrib": 5,
            "status": 1
          },
          "booleanAnd": true,
          "beginsGrouping": false,
          "endsGrouping": false
        }
      ]
    }
  ]
}

**Comment by RealRaven2000** [comment] 2021-11-29 11:03
> If I create a subject filter on my personal gmail account this works, that is why I thought it was exquilla related.

I think exquilla is just setting up a middleware mechanism to pull your mail from the exchange server; I don't think it does anything with filters (which still only run locally on Thunderbird; Tb cannot upload filters to any type of server and run them there)

> If I run the one filter manually nothing happens, also no output in the filter log. If I try to run a backup of the filters there is no screen to select the output file. 

That's strange, may it be a side effect from your invalid license? Contact me directly to get a different license for your Exchange account - it seems the email address that is set up as your default identity isn't the one in the key.

> On my work computer this screen exists. I'm using my license on two laptops, thought that was permitted. Attached are the screenshots.The email account m.r.*@*********** i the exquilla (exchange) work account.

It is permitted - but check what email address is set up in account settings / default identity:
![image](https://user-images.githubusercontent.com/6314674/143856627-3abf37b6-f60d-427d-aff3-2776dbf4f241.png)
These (default addresses) are the ones quickFilters checks against the one in the license key!

**Comment by sandwitch** [comment] 2021-12-02 05:23
I checked the default identity  settings for this account, they are correct. However I use two more (private gmail accounts). So the default account email address is the same as in the license i got from you.
The only thing quickfilter does is enabling the creation of filters isn't it? The filtering itself is done by TB I guess. So the problem with filtering should be at TB?

Regards
M

**Comment by RealRaven2000** [comment] 2021-12-02 10:29
> I checked the default identity settings for this account, they are correct. However I use two more (private gmail accounts). So the default account email address is the same as in the license i got from you. The only thing quickfilter does is enabling the creation of filters isn't it? The filtering itself is done by TB I guess. So the problem with filtering should be at TB?

This is correct - it only plays a role if you use "list-id" which is an additional search condition that quickFilters adds. Other than that, it can be used for management, creation and testing of filters. And you can keep using these filters even after you have uninstalled quickFilters.

**Comment by sandwitch** [comment] 2021-12-02 11:11
Well if we can solve the problem with the subscription. I think you helped
me fantastic. For the rest I will contact TB if needed  Btw I installed
filterquila and with the regex function everything works as expected.
Regards Mark

Op do 2 dec. 2021 11:29 schreef RealRaven2000 ***@***.***>:

**Comment by RealRaven2000** [comment] 2021-12-02 11:47
> Well if we can solve the problem with the subscription. I think you helped me fantastic. For the rest I will contact TB if needed Btw I installed filterquila and with the regex function everything works as expected.

Good to know - and thanks for subscribing. By the way I had taken over FiltaQuilla from the original developer who had to abandon it due to illness and I am aware that there are currently many regressions caused by Thunderbird 91, partly depending on changes on their side for fixes. The release there is a little slow because it is a minefield - it is a very "low-level" piece of code and there is no financial pressure / support on that side to warrant overspending time on it; but I am trudging along and uploading new test versions to its [issue tracker](https://github.com/RealRaven2000/FiltaQuilla/issues) regularly.

Closing this issue for now.

**Closed by RealRaven2000** 2021-12-02 11:47 UTC
