### ISSUE TITLE
quickFilters toolbar button is always active

### ISSUE THREAD

**Issue by ThiloteE** [RealRaven2000/quickFilters#223] opened 2023-10-29 08:46 UTC
System: Windows 10, Betterbird 115.4

How it looks like:
![image](https://github.com/RealRaven2000/quickFilters/assets/73715071/e634e257-a304-406b-8317-fbd4ef65fe3d)

How it is supposed to look like:
![image](https://github.com/RealRaven2000/quickFilters/assets/73715071/fc5e7da1-1d74-40b1-a4e9-9585f4f279b9)

How to reproduce:

1. Start Betterbird.
2. See that the QuickFilter toolbar button does **NOT** shine. (good)
3. Click the QuickFilter toolbar button.
4. Click somewhere else in the Betterbird UI.
5. See that the QuickFilter toolbar button does continue to shine. (bad)
6. Restart Betterbird
7. See that the QuickFilter toolbar button does not shine. (good).

**Comment by RealRaven2000** [comment] 2023-10-29 14:42
When you say "shine", you probably mean an outline in dark mode, like this:

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/c9945a5f-b02b-409a-91f7-90b705948226)

I am doing some none-standard styling and am currently not using the pure API to build the menu, instead inject it using the experimental WindowListener API.

one of my main reasons for this is the handling of updates, because I do not like popup windows that are just shown to the user arbitrarily. instead I like to restyle the button and ask the user to click it when they have time for it. 

It seems like the styling is caused by the attribute `aria-pressed="true"` - which is something that should be removed automatically when another screen element is pushed or the popup menu is closed. Maybe I need to monitor this manually somehow and add event listeners for it losing focus to fix it.

**Comment by ThiloteE** [comment] 2023-10-29 15:59
Hey Axel, yes you go tthat right. I mean the outline in darkmode.
Thank you for your consideration.

**Comment by RealRaven2000** [comment] 2024-08-09 16:35
This is cause by the attribute `aria-pressed="false"` on the button element. I currently add the menu with a non-standard way (through injection). need to rewrite via the API, but this would also destroy the news/ license features, so I need to tread carefully here as I do not want to lose this important functionality (it pays for all the work through licensing).

However I can deal with this now by removing the attribute when a command from the menu is executed. Fix incoming ASAP.

**Comment by RealRaven2000** [comment] 2024-08-09 16:47
Here you go. Better late than never.

[quickFilters-wx-6.5.2pre41.zip](https://github.com/user-attachments/files/16564520/quickFilters-wx-6.5.2pre41.zip)

This version also contains redesigned svg icons that work better with dark themes.

----

To install, download archive and drop into Thunderbird Add-ns Manager (without extracting contents). I will close the bug myself when I publish the next version.

**Comment by ThiloteE** [comment] 2024-08-09 19:19
Hah! Thanks Axel! Has been a while indeed, but great that you found a fix.

**Comment by RealRaven2000** [comment] 2024-08-10 09:08
> Hah! Thanks Axel! Has been a while indeed, but great that you found a fix.

you're welcome. Fix was actually very easy once I got into it and I thought after delving down the rabbit hole for 3 days to fix those pesky icons (I will document this in detail at #259 when I get time, but it really took up a load of my hours over the last 2 weeks), I glimpsed this one and added it as a bonus.

**Comment by RealRaven2000** [comment] 2024-08-10 17:12
Fixed in 6.5.2 - Published 09/08/2024

**Closed as completed by RealRaven2000** 2024-08-10 17:12 UTC
