### ISSUE TITLE
"Create Filters" (quickFilters Assistant) when deleting - can it be disabled?

### ISSUE THREAD

**Issue by aprojanos71** [RealRaven2000/quickFilters#162] opened 2023-02-18 07:38 UTC
5.8 when I delete the messeage(s),  pop up "Create Filters" window.

**Comment by tuxy123** [comment] 2023-02-18 09:50
> 5.8 when I delete the messeage(s), pop up "Create Filters" window.

I have the same issue

**Comment by RealRaven2000** [comment] 2023-02-18 10:44
This is a duplicate of #158 

> Being able to create filters that delete mail is by design, and you can disable it with the new button on the filter actions page in quickFilters settings. Only affects users who have the filter assistant switched on permanently, but it's definitely more useful than only doing it when dragging mail to trash. See also https://github.com/RealRaven2000/quickFilters/issues/155 (Switching off quickFilters for delete and archive destroys my main use case) for a deeper discussion.


![image](https://user-images.githubusercontent.com/6314674/219310676-03d346d5-a268-4d47-b648-7d403d48c5e5.png)

set `extensions.quickfilters.assistant.exclude.trash = true`

> Normally you would switch on the assistant with the intent to create new filters (or add rules to a filter that may also delete mail as a possible action) - this way you can discover the feature without any learning curve.

> I believe this default will benefit the larger number of users, rather than the few people who run the assistant constantly - to switch  on auto assistant you are on the same settings page (actions), which is something an advanced user might enable.

I also added Screenshots to the version history page at quickfolders.org that explain in detail:

https://quickfilters.quickfolders.org/version.html#5.18

**Comment by RealRaven2000** [comment] 2023-04-11 11:10
Duplicate of #158

**Closed by RealRaven2000** 2023-04-11 11:11 UTC
Labels: question
