### ISSUE TITLE
Save attachment to dropping first backslash

### ISSUE THREAD

**Issue by eng957** [RealRaven2000/quickFilters#94] opened 2022-02-17 17:57 UTC
Save attachment to only saves to a network location the first time then drops the first backslash causing it to fail to do anything.   After adding the backslash back and trying again it saves a blank file then removes the first backslash.

**Comment by RealRaven2000** [comment] 2022-02-17 20:26
wrong github - this is a request for FiltaQuilla. 

I am marking this as duplicate of 
https://github.com/RealRaven2000/FiltaQuilla/issues/79

it is caused by the way THUNDERBIRD stores conditions.

**Closed by RealRaven2000** 2022-02-17 20:26 UTC

**Comment by eng957** [comment] 2022-02-17 22:16
I am new to this github bug reporting so help me understand what this means to close this issue and refer me to another closed issue with no apparent solution in either other than some work around involving modifying a configuration file.

**Comment by RealRaven2000** [comment] 2022-02-17 22:24
> I am new to this github bug reporting so help me understand what this means to close this issue and refer me to another closed issue with no apparent solution in either other than some work around involving modifying a configuration file.

it means that the function "save attachment" is not from quickFilters. it's from another Add-on names FiltaQuilla, and the bug there reports the same issue. It can only be fixed in FiltaQuilla.  I am only using some pages on my quickFIlters add-on for documentation of FiltaQuilla (which I inherited from its author Kent James). The bug discusses workarounds, I haven't been able to fix it so far, no matter what I do Thunderbird drops one of the backslashes. Addons can unfortunately not change the way Thunderbird saves its values, it's hardcoded in the back end and written in C++. So the problem is in Thunderbird Core code here.
