### ISSUE TITLE
Filters have to be created multiple time and the oldest have empty searchTerms

### ISSUE THREAD

**Issue by cbroult** [RealRaven2000/quickFilters#13] opened 2020-05-27 15:31 UTC
For several months I have notice that I had to regularly recreate some filters.
Now I can no longer right click on Inbox > Run filters since that reports that many of my filters are failing to apply.

Saving the filters I can see that for some filters several entries exist that are empty (see 
[cbroult@yahoo.com_2020-05-27_17-16.txt](https://github.com/RealRaven2000/quickFilters/files/4689720/cbroult%40yahoo.com_2020-05-27_17-16.txt)) 

I have no idea as to why there is such a problem. I reckon that I have a very large amount of filters...

Please let me know how I can best help to fix that issue that seems to be related to https://www.mozdev.org/bugs/show_bug.cgi?id=26710.

**Comment by RealRaven2000** [comment] 2020-05-27 20:00
Did you try the "troubleshooting" feature?
![image](https://user-images.githubusercontent.com/6314674/83066542-1d2b4880-a05d-11ea-89d1-a15b228a19f8.png)

**Comment by cbroult** [comment] 2020-05-28 09:05
Indeed I tried that button several times. Though it seems that nothing happens when I pressed it. I guess I am going to manually the JSON file and import it again to come to a clean state and monitor my filter list. If the issue is still present I am going to comment again on that ticket.

**Comment by cbroult** [comment] 2020-06-07 11:20
I decided to start from scratch and recreate my filters one by one. Now I end up in a similar situation where a lot of searchTerms in the exported JSON are empty ([cbroult@yahoo.com_2020-06-07_13-03.cleaned.json.txt](https://github.com/RealRaven2000/quickFilters/files/4741921/cbroult%40yahoo.com_2020-06-07_13-03.cleaned.json.txt)) which causes a Run Filters on my Inbox to report multiple failures.
 
Using a script I removed the filters with empty searchTerms and after removing all the filters and importing the cleaned filters ([cbroult@yahoo.com_2020-06-07_13-03.json.txt](https://github.com/RealRaven2000/quickFilters/files/4741922/cbroult%40yahoo.com_2020-06-07_13-03.json.txt)) then Run Filters is successful.

What should I be doing to help troubleshoot that issue?

**Comment by RealRaven2000** [comment] 2020-06-07 12:08
if you can reproduce creating a filter with empty conditions please make a step by step description here (with screenshots). 

- Which quickFilter template are you using to create the filter? Is it created on "move mail" with active quickFilters assistant, or "after the fact" (by right-clicking an email that is already in a non-Inbox folder and using "quickFilters: create filter from message"):
![image](https://user-images.githubusercontent.com/6314674/83968255-c70d9f00-a8bf-11ea-90a7-356ee12edb10.png)

- What kind of search conditions  are failing?
- Are the condition values a problem? (e.g. name or email address with diacritics / umlauts / non-ASCII characters
- What is your default action for the filter?
- do you use non-standard search conditions (e.g. the ones provided by FiltaQuilla)?

**Comment by RealRaven2000** [comment] 2020-10-30 10:00
Should I leave this issue open or close it? It still looks like it might be cause by a corrupted profile... A developer friend of mine said he recreates a fresh profile for all his production mail every year; I only repair folders from time to time. It doesn't seem like this is easily reproducible and almost certainly not fixable in the quickFilters codebase. So it is very very likely a Thundebird bug - or a whole group of bugs.

**Closed by RealRaven2000** 2020-10-30 10:00 UTC

**Comment by RealRaven2000** [comment] 2023-08-28 12:21
> I decided to start from scratch and recreate my filters one by one. Now I end up in a similar situation where a lot of searchTerms in the exported JSON are empty ([cbroult@yahoo.com_2020-06-07_13-03.cleaned.json.txt](https://github.com/RealRaven2000/quickFilters/files/4741921/cbroult%40yahoo.com_2020-06-07_13-03.cleaned.json.txt)) which causes a Run Filters on my Inbox to report multiple failures.

I wonder if something happened with the copy terms routine to fail. If you still use quickFIlt4ers, check the latest version and the error console (Ctrl+Shift+J) after creating a filter and when exporting.
