### ISSUE TITLE
Thunderbird 100.0b2 (64-bit)

### ISSUE THREAD

**Issue by aprojanos71** [RealRaven2000/quickFilters#99] opened 2022-04-17 10:02 UTC
![image](https://user-images.githubusercontent.com/6314674/163727793-6d22e35a-5ae2-4b05-a55d-d444d85b14d0.png)

**Comment by aprojanos71** [comment] 2022-04-17 15:23
Not working.

**Comment by aprojanos71** [comment] 2022-04-17 17:08
When I start the Quickfilter, a yellow error message pops up below and I can't exit Thunderbird.
And where are my filters?

**Comment by aprojanos71** [comment] 2022-04-17 17:09
Is the license expired ???

**Comment by RealRaven2000** [comment] 2022-04-17 18:34
duplicate of issue #97 - please try the versions uploaded there for running Thunderbird betas.
https://github.com/RealRaven2000/quickFilters/issues/97

**Comment by RealRaven2000** [comment] 2022-04-17 18:34
please don't link to external content (as you did previously) - you can paste images here directly:

> ![image](https://user-images.githubusercontent.com/6314674/163727793-6d22e35a-5ae2-4b05-a55d-d444d85b14d0.png)

**Closed by RealRaven2000** 2022-04-17 18:34 UTC
